---
title: "Workshop 5"
author: "Ozan Aksut"
date: "22/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(scales)
library(lubridate)
theme_set(theme_light())

```

```{r}
survey <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-05-18/survey.csv')

```




```{r}
survey <- survey %>%
  mutate(timestamp = mdy_hms(timestamp),
         age_category = fct_relevel(fct_reorder(how_old_are_you, parse_number(how_old_are_you)), "under 18"),
         experience_overall = str_replace(overall_years_of_professional_experience, " - ", "-"),
         experience_overall = fct_reorder(experience_overall, parse_number(experience_overall)),
         experience_in_field = str_replace(years_of_experience_in_field, " - ", "-"),
         experience_in_field = fct_reorder(experience_in_field, parse_number(experience_in_field))) %>%
  mutate(gender = fct_collapse(coalesce(gender, "Other or prefer not to answer"), "Other or prefer not to answer" = c("Other or prefer not to answer", "Prefer not to answer")),
         race = fct_lump(coalesce(race, "Other"), 4),
         age=parse_number(how_old_are_you))

survey_usd <- survey %>%
  filter(currency == "USD") %>%
  filter(annual_salary >= 5000,
         annual_salary <= 2e6) %>%
  mutate(state = str_remove(state, ", .*"))

```



```{r}
survey_usd %>%
  ggplot(aes(annual_salary)) +
  geom_histogram() 

```



```{r}
survey_usd %>%
  ggplot(aes(x = age, y = annual_salary)) +
  geom_point(colour = "purple")

```





```{r}
survey_usd %>%
  ggplot(aes(age,annual_salary)) +
  geom_col(colour = "red")

```


```{r}
survey_usd %>%
count(experience_overall)
```



```{r}
survey_usd %>%
  ggplot(aes(age,annual_salary, fill=gender)) +
  geom_col()+
  coord_flip()

```


```{r}

survey_usd %>%
  ggplot(aes(age,annual_salary, colour=gender)) +
  geom_col()+
  coord_flip()

```




```{r}
survey_usd %>%
  ggplot(aes(age,annual_salary, fill=race)) +
  geom_col()+
  coord_flip()

```


```{r}
survey_usd %>%
  ggplot(aes(age,annual_salary)) +
  geom_col()+
  coord_flip()

```



```{r}
survey_usd %>%
  ggplot(aes(annual_salary)) +
  geom_histogram() +
  scale_x_log10(labels = dollar_format()) +
  labs(x = "Annual")
```



































